CREATE TABLE person (
    ID int,
    Name varchar(40)
);

INSERT INTO PERSON (ID, NAME) VALUES (1, 'Omer');
INSERT INTO PERSON (ID, NAME) VALUES (2, 'Ali');
INSERT INTO PERSON (ID, NAME) VALUES (3, 'Ahmet');